apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zeloo
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - zeloo.example.com
    secretName: zeloo-tls
  rules:
  - host: zeloo.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zeloo
            port:
              number: 80