apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zeloo.fullname" . }}
  labels:
    {{- include "zeloo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zeloo.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
  template:
    metadata:
      labels:
        {{- include "zeloo.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "zeloo.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.httpTargetPort }}
        - name: metrics
          containerPort: {{ .Values.service.metricsTargetPort }}
        env:
        - name: zeloo_HOME
          value: {{ .Values.persistence.mountPath | quote }}
        - name: zeloo_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: {{ include "zeloo.configMapName" . }}
              key: provider
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "zeloo.secretName" . }}
              key: openai-api-key
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        securityContext:
          runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
        volumeMounts:
        {{- if .Values.persistence.enabled }}
        - name: data
          mountPath: {{ .Values.persistence.mountPath }}
        {{- end }}
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "zeloo.pvcName" . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}