"""Meta-Prompt engine — generate, optimize, and refine prompts via LLM."""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    pass

logger = logging.getLogger(__name__)


@dataclass
class MetaPromptVariant:
    """A prompt variant generated by meta-prompting."""

    variant_id: str
    original_prompt: str
    refined_prompt: str
    technique: str
    rationale: str
    expected_improvement: str
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class MetaPromptResult:
    """Result of meta-prompt generation."""

    original_prompt: str
    variants: list[MetaPromptVariant]
    recommended_variant_id: str | None = None
    total_variants: int = 0


class MetaPromptEngine:
    """Generate improved prompt variants using LLM-driven meta-prompting.

    Uses chain-of-thought reasoning to:
    1. Analyze the original prompt's weaknesses
    2. Apply known prompt engineering techniques
    3. Generate multiple variants
    4. Recommend best candidate
    """

    META_PROMPT_TEMPLATE = """You are an expert prompt engineer. Analyze the
following prompt and generate 3 improved variants.

ORIGINAL PROMPT:
{prompt}

TASK CONTEXT:
{task_context}

For each variant, apply one of these techniques:
1. "specificity" — Make instructions more specific and concrete
2. "structure" — Add clear structure with sections (Role, Task, Format, Constraints)
3. "examples" — Add 1-2 concrete few-shot examples
4. "constraints" — Add explicit constraints and guardrails
5. "persona" — Add a clear role/persona definition

Output ONLY valid JSON in this exact format:
{{
  "variants": [
    {{
      "technique": "specificity|structure|examples|constraints|persona",
      "refined_prompt": "the complete improved prompt text",
      "rationale": "one-sentence explanation",
      "expected_improvement": "specific metric or behavior expected to improve"
    }}
  ],
  "recommended_index": 0
}}"""

    HEURISTIC_TECHNIQUES: dict[str, callable] = None  # type: ignore

    def __init__(self, llm_provider: Any | None = None) -> None:
        self.llm_provider = llm_provider

    def generate_variants(
        self,
        prompt: str,
        task_context: str = "",
        num_variants: int = 3,
    ) -> MetaPromptResult:
        """Generate prompt variants."""
        if self.llm_provider is not None:
            return self._generate_with_llm(prompt, task_context, num_variants)
        return self._generate_heuristic(prompt, task_context, num_variants)

    def _generate_with_llm(
        self,
        prompt: str,
        task_context: str,
        num_variants: int,
    ) -> MetaPromptResult:
        """Generate variants using LLM."""
        meta_prompt = self.META_PROMPT_TEMPLATE.format(
            prompt=prompt,
            task_context=task_context or "general purpose task",
        )

        try:
            response = self.llm_provider.chat_completion(
                messages=[
                    {
                        "role": "system",
                        "content": "You are a prompt engineering expert. Output only JSON.",
                    },
                    {"role": "user", "content": meta_prompt},
                ],
                temperature=0.7,
            )
            content = response.content if hasattr(response, "content") else str(response)
            parsed = json.loads(content)
            variants = []
            for i, v in enumerate(parsed.get("variants", [])[:num_variants]):
                variants.append(
                    MetaPromptVariant(
                        variant_id=f"meta_{i}_{v['technique']}",
                        original_prompt=prompt,
                        refined_prompt=v["refined_prompt"],
                        technique=v["technique"],
                        rationale=v.get("rationale", ""),
                        expected_improvement=v.get("expected_improvement", ""),
                    )
                )
            recommended_index = parsed.get("recommended_index", 0)
            recommended_id = (
                variants[recommended_index].variant_id
                if 0 <= recommended_index < len(variants)
                else None
            )
            return MetaPromptResult(
                original_prompt=prompt,
                variants=variants,
                recommended_variant_id=recommended_id,
                total_variants=len(variants),
            )
        except Exception as e:
            logger.warning("LLM meta-prompting failed: %s, falling back to heuristic", e)
            return self._generate_heuristic(prompt, task_context, num_variants)

    def _generate_heuristic(
        self,
        prompt: str,
        task_context: str,
        num_variants: int,
    ) -> MetaPromptResult:
        """Generate variants using rule-based transformations."""
        variants = []

        variants.append(MetaPromptVariant(
            variant_id="meta_0_specificity",
            original_prompt=prompt,
            refined_prompt=self._apply_specificity(prompt),
            technique="specificity",
            rationale="Added explicit constraints and formatting",
            expected_improvement="Better adherence to output format",
        ))

        if num_variants >= 2:
            variants.append(MetaPromptVariant(
                variant_id="meta_1_structure",
                original_prompt=prompt,
                refined_prompt=self._apply_structure(prompt),
                technique="structure",
                rationale="Added structured sections (Role/Task/Format/Constraints)",
                expected_improvement="Clearer understanding of expectations",
            ))

        if num_variants >= 3:
            variants.append(MetaPromptVariant(
                variant_id="meta_2_persona",
                original_prompt=prompt,
                refined_prompt=self._apply_persona(prompt),
                technique="persona",
                rationale="Added expert role definition",
                expected_improvement="Higher quality domain-specific responses",
            ))

        if num_variants >= 4:
            variants.append(MetaPromptVariant(
                variant_id="meta_3_examples",
                original_prompt=prompt,
                refined_prompt=self._apply_examples(prompt),
                technique="examples",
                rationale="Added few-shot examples structure",
                expected_improvement="More predictable outputs",
            ))

        if num_variants >= 5:
            variants.append(MetaPromptVariant(
                variant_id="meta_4_constraints",
                original_prompt=prompt,
                refined_prompt=self._apply_constraints(prompt),
                technique="constraints",
                rationale="Added explicit constraints and edge cases",
                expected_improvement="Fewer hallucination/edge-case errors",
            ))

        recommended_id = variants[0].variant_id if variants else None
        return MetaPromptResult(
            original_prompt=prompt,
            variants=variants,
            recommended_variant_id=recommended_id,
            total_variants=len(variants),
        )

    def _apply_specificity(self, prompt: str) -> str:
        return (
            f"{prompt.strip()}\n\n"
            "Be specific and concise. Use clear language.\n"
            "If unsure, state your confidence level."
        )

    def _apply_structure(self, prompt: str) -> str:
        return (
            "## Role\nYou are a helpful AI assistant.\n\n"
            f"## Task\n{prompt.strip()}\n\n"
            "## Format\nProvide a clear, structured response.\n\n"
            "## Constraints\n"
            "- Be accurate\n"
            "- Be concise\n"
            "- Cite sources when applicable"
        )

    def _apply_persona(self, prompt: str) -> str:
        return (
            "You are an expert with 20+ years of experience. "
            f"Your task: {prompt.strip()}\n\n"
            "Apply professional standards and provide detailed insights."
        )

    def _apply_examples(self, prompt: str) -> str:
        return (
            f"{prompt.strip()}\n\n"
            "Example 1:\nInput: [sample input]\n"
            "Output: [expected output]\n\n"
            "Example 2:\nInput: [another input]\n"
            "Output: [another output]\n\n"
            "Follow these patterns for your response."
        )

    def _apply_constraints(self, prompt: str) -> str:
        return (
            f"{prompt.strip()}\n\n"
            "Constraints:\n"
            "- Output must be under 500 words\n"
            "- Avoid speculation — state assumptions explicitly\n"
            "- Do not include apologies or disclaimers\n"
            "- If you cannot answer, say 'I don't know'"
        )

    def apply_variant(
        self,
        variant: MetaPromptVariant,
        compressor: Any | None = None,
    ) -> str:
        """Apply a variant, optionally compressing the result."""
        text = variant.refined_prompt
        if compressor is not None:
            result = compressor.compress(text)
            return result.compressed_text
        return text


__all__ = [
    "MetaPromptVariant",
    "MetaPromptResult",
    "MetaPromptEngine",
]