"""``/spec`` — SPEC MODE: authoritative three-document specification + task planning.

SPEC MODE is for complex projects where the plan needs to be frozen as reference before
execution begins.  Unlike /plan (informal, always editable), SPEC MODE produces:

  .Zeloo/specs/<slug>/
    spec.md       — what to build and why
    tasks.md      — ordered task list with acceptance criteria
    checklist.md  — per-task acceptance checklist

Documents are written to disk by the agent in this turn (plan_prompt.py rules apply:
read-only inspection, no mutations except writing the three documents).  No execution.
"""

from __future__ import annotations

_SPEC_MODE_RULES = """\
For this turn, you are in SPEC MODE — write authoritative specification documents.

- Do not implement code.
- Do not edit any project files except the three documents under .Zeloo/specs/<slug>/.
- Do not run mutating terminal commands, commit, push, or external actions.
- You may inspect the workspace with read-only tools when needed.
- Your deliverable is three markdown files saved under .Zeloo/specs/<slug>/ (create
  the directory and all three files in this turn).
"""

_SPEC_CRAFT = """\
Write the three SPEC MODE documents for an implementer who has zero context and
questionable taste.  A good spec makes implementation obvious.

---

SPEC.md (what & why)
  - Summary — one sentence, concrete outcome.
  - Motivation — why this matters, problem being solved.
  - User stories — concrete examples of how a user experiences the feature.
  - Non-goals — explicitly out of scope.
  - Constraints — budget, timeline, tech stack, team size.
  - Open questions — things that need a decision before coding.

---

tasks.md (how, in order)
  Each task:
    ## N. <Task name>

    **Input:**  what this task gets as input.
    **Output:**  what this task produces.
    **Files:**   exact file paths touched (src/foo.py, not "the model file").
    **Test:**    exact command + expected output to verify the task is done.
    **Accept:**  one or more concrete acceptance criteria (observable, testable).

  Keep tasks bite-sized (30-90 min of focused work).  Order respects dependencies.

---

checklist.md (when done)
  For each task in tasks.md:

    ## N. <Task name>

    - [ ] <first concrete acceptance criterion>
    - [ ] <second concrete acceptance criterion>
    - [ ] ...

  All criteria must be [x] before the task is COMPLETE.
  Keep criteria specific and testable — not "it works" but "curl /api/user/1
  returns 200 with id==1 and name=='Alice'".

---

Interaction style:
  If the request is clear, write all three documents now.
  If genuinely underspecified, ask one focused clarifying question before writing.
  Save documents as .Zeloo/specs/<slug>/spec.md, tasks.md, checklist.md.
  After saving, reply with a one-line summary of the spec and the three file paths.
  Do NOT start executing in this turn.
"""

def build_spec_prompt(task: str = "", slug: str = "") -> str:
    """Build the SPEC MODE prompt.

    *task*  — the feature/change being specified (optional; empty means infer from
               conversation context).
    *slug*  — already-chosen directory name (optional; if empty the agent invents one).

    Returns a string that is injected into the agent as a normal turn (prompt-cache safe,
    no engine, no model-tool footprint — identical to /plan).
    """
    task = (task or "").strip()
    slug = (slug or "").strip()

    task_block = f"Feature to specify:\n{task}\n" if task else (
        "No explicit feature was given with /spec — infer the task from the "
        "current conversation context (the thing we have been discussing). "
        "If nothing is implied, ask a brief clarifying question before writing.\n"
    )

    slug_block = f"Spec directory:\n  .Zeloo/specs/{slug}/\n" if slug else (
        "Spec directory: .Zeloo/specs/<auto-generated-slug>/\n"
    )

    return (
        "[/spec — SPEC MODE]\n\n"
        + _SPEC_MODE_RULES + "\n\n"
        + task_block + "\n"
        + slug_block + "\n"
        + _SPEC_CRAFT + "\n"
    )
